"""changed savedq foreign key rel to username

Revision ID: 05e643305155
Revises: f190c6d8dda1
Create Date: 2021-08-10 19:15:45.304245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e643305155'
down_revision = 'f190c6d8dda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_query', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('key_unique_user_and_query', 'saved_query', type_='unique')
    op.create_unique_constraint('key_unique_username_and_query', 'saved_query', ['username', 'query'])
    op.drop_constraint('saved_query_user_id_fkey', 'saved_query', type_='foreignkey')
    op.create_foreign_key(None, 'saved_query', 'user', ['username'], ['username'])
    op.drop_column('saved_query', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_query', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_query', type_='foreignkey')
    op.create_foreign_key('saved_query_user_id_fkey', 'saved_query', 'user', ['user_id'], ['id'])
    op.drop_constraint('key_unique_username_and_query', 'saved_query', type_='unique')
    op.create_unique_constraint('key_unique_user_and_query', 'saved_query', ['user_id', 'query'])
    op.drop_column('saved_query', 'username')
    # ### end Alembic commands ###
