"""empty message

Revision ID: 10e4b48cd2d2
Revises: 
Create Date: 2021-08-27 14:58:57.541090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e4b48cd2d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('pricechange', sa.Numeric(), nullable=True),
    sa.Column('percentchange', sa.Numeric(), nullable=True),
    sa.Column('exchangename', sa.Text(), nullable=True),
    sa.Column('exshortname', sa.Text(), nullable=True),
    sa.Column('exchangecode', sa.Text(), nullable=True),
    sa.Column('marketplace', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('openprice', sa.Numeric(), nullable=True),
    sa.Column('dayhigh', sa.Numeric(), nullable=True),
    sa.Column('daylow', sa.Numeric(), nullable=True),
    sa.Column('marketcap', sa.BigInteger(), nullable=True),
    sa.Column('marketcapallclasses', sa.BigInteger(), nullable=True),
    sa.Column('peratio', sa.Numeric(), nullable=True),
    sa.Column('prevclose', sa.Numeric(), nullable=True),
    sa.Column('dividendfrequency', sa.Text(), nullable=True),
    sa.Column('dividendyield', sa.Numeric(), nullable=True),
    sa.Column('dividendamount', sa.Numeric(), nullable=True),
    sa.Column('dividendcurrency', sa.Text(), nullable=True),
    sa.Column('beta', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('exdividenddate', sa.DateTime(), nullable=True),
    sa.Column('shortdescription', sa.Text(), nullable=True),
    sa.Column('longdescription', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phonenumber', sa.Text(), nullable=True),
    sa.Column('fulladdress', sa.Text(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('shareoutstanding', sa.BigInteger(), nullable=True),
    sa.Column('totaldebttoequity', sa.Numeric(), nullable=True),
    sa.Column('totalsharesoutstanding', sa.BigInteger(), nullable=True),
    sa.Column('sharesescrow', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Numeric(), nullable=True),
    sa.Column('dividendpaydate', sa.DateTime(), nullable=True),
    sa.Column('weeks52high', sa.Numeric(), nullable=True),
    sa.Column('weeks52low', sa.Numeric(), nullable=True),
    sa.Column('alpha', sa.Numeric(), nullable=True),
    sa.Column('averagevolume10d', sa.BigInteger(), nullable=True),
    sa.Column('averagevolume30d', sa.BigInteger(), nullable=True),
    sa.Column('averagevolume50d', sa.BigInteger(), nullable=True),
    sa.Column('pricetobook', sa.Numeric(), nullable=True),
    sa.Column('pricetocashflow', sa.Numeric(), nullable=True),
    sa.Column('returnonequity', sa.Numeric(), nullable=True),
    sa.Column('returnonassets', sa.Numeric(), nullable=True),
    sa.Column('day21movingavg', sa.Numeric(), nullable=True),
    sa.Column('day50movingavg', sa.Numeric(), nullable=True),
    sa.Column('day200movingavg', sa.Numeric(), nullable=True),
    sa.Column('dividend3years', sa.Numeric(), nullable=True),
    sa.Column('dividend5years', sa.Numeric(), nullable=True),
    sa.Column('datatype', sa.Text(), nullable=True),
    sa.Column('typename', sa.Text(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.Column('lastupdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'name', name='quotes_symbol_name_key')
    )
    op.create_index(op.f('ix_quote_lastupdate'), 'quote', ['lastupdate'], unique=False)
    op.create_index(op.f('ix_quote_symbol'), 'quote', ['symbol'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('saved_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('year', sa.String(length=30), nullable=True),
    sa.Column('month', sa.String(length=30), nullable=True),
    sa.Column('day', sa.String(length=30), nullable=True),
    sa.Column('week', sa.String(length=30), nullable=True),
    sa.Column('day_of_week', sa.String(length=30), nullable=True),
    sa.Column('hour', sa.String(length=30), nullable=True),
    sa.Column('minute', sa.String(length=30), nullable=True),
    sa.Column('second', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'query', 'year', 'month', 'day', 'hour', 'minute', name='key_unique_user_query_time')
    )
    op.create_index(op.f('ix_saved_query_created'), 'saved_query', ['created'], unique=False)
    op.create_index(op.f('ix_saved_query_title'), 'saved_query', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_query_title'), table_name='saved_query')
    op.drop_index(op.f('ix_saved_query_created'), table_name='saved_query')
    op.drop_table('saved_query')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_quote_symbol'), table_name='quote')
    op.drop_index(op.f('ix_quote_lastupdate'), table_name='quote')
    op.drop_table('quote')
    # ### end Alembic commands ###
