"""empty message

Revision ID: 1e6940cca952
Revises: f0895f52eb66
Create Date: 2021-05-05 15:57:00.069716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6940cca952'
down_revision = 'f0895f52eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('delisted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'delisted')
    # ### end Alembic commands ###
