"""added run_date to savedquery

Revision ID: 2a04536c206b
Revises: 05e643305155
Create Date: 2021-08-10 19:37:39.095872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a04536c206b'
down_revision = '05e643305155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_query', sa.Column('run_day', sa.Date(), nullable=False))
    op.add_column('saved_query', sa.Column('run_time', sa.Time(), nullable=False))
    op.drop_column('saved_query', 'run_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_query', sa.Column('run_at', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('saved_query', 'run_time')
    op.drop_column('saved_query', 'run_day')
    # ### end Alembic commands ###
