"""added lastupdate field to quote

Revision ID: 709432d2313c
Revises: 95e5d56ec2d7
Create Date: 2021-04-24 17:23:21.936053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709432d2313c'
down_revision = '95e5d56ec2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('lastupdate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_quote_lastupdate'), 'quote', ['lastupdate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_lastupdate'), table_name='quote')
    op.drop_column('quote', 'lastupdate')
    # ### end Alembic commands ###
