"""quote symbol explicitly uniquer

Revision ID: 95e5d56ec2d7
Revises: 9c8ddc40e8dd
Create Date: 2021-04-24 15:17:43.511782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e5d56ec2d7'
down_revision = '9c8ddc40e8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_symbol', table_name='quote')
    op.create_index(op.f('ix_quote_symbol'), 'quote', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_symbol'), table_name='quote')
    op.create_index('ix_quote_symbol', 'quote', ['symbol'], unique=False)
    # ### end Alembic commands ###
