"""quote filed update

Revision ID: 9c8ddc40e8dd
Revises: c2bf4cd60f1c
Create Date: 2021-04-24 15:14:58.803777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8ddc40e8dd'
down_revision = 'c2bf4cd60f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('typename', sa.Text(), nullable=True))
    op.drop_constraint('uix_symbol_name', 'quote', type_='unique')
    op.create_unique_constraint('quotes_symbol_name_key', 'quote', ['symbol', 'name'])
    op.drop_column('quote', '_Quote__typename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('_Quote__typename', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('quotes_symbol_name_key', 'quote', type_='unique')
    op.create_unique_constraint('uix_symbol_name', 'quote', ['symbol', 'name'])
    op.drop_column('quote', 'typename')
    # ### end Alembic commands ###
