"""update savedquery

Revision ID: 9efaaa5f0b4e
Revises: 4534be228665
Create Date: 2021-05-25 18:05:31.335806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efaaa5f0b4e'
down_revision = '4534be228665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_query', sa.Column('run_at', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_query', 'run_at')
    # ### end Alembic commands ###
