"""update savedquery

Revision ID: ac0ae41cd272
Revises: b3630da8c4dd
Create Date: 2021-05-25 18:00:06.848225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0ae41cd272'
down_revision = 'b3630da8c4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_query', sa.Column('run_at2', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_query', 'run_at2')
    # ### end Alembic commands ###
