"""cahnges user and saved query

Revision ID: f0895f52eb66
Revises: 709432d2313c
Create Date: 2021-04-24 19:12:08.373988

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = "f0895f52eb66"
down_revision = "709432d2313c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("saved_query", sa.Column("frequency", sa.String(length=30)))
    op.execute("UPDATE saved_query SET frequency = 'daily'")
    op.alter_column("saved_query", "frequency", nullable=False)
    op.add_column("saved_query", sa.Column("run_at", sa.DateTime()))
    op.execute(f"UPDATE saved_query SET run_at = '{datetime.utcnow()}'")
    op.alter_column("saved_query", "run_at", nullable=False)
    op.alter_column("user", "firstname", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "firstname", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_column("saved_query", "run_at")
    op.drop_column("saved_query", "frequency")
    # ### end Alembic commands ###
