"""empty message

Revision ID: f190c6d8dda1
Revises: 9efaaa5f0b4e
Create Date: 2021-08-10 17:40:40.975171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f190c6d8dda1'
down_revision = '9efaaa5f0b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index('ix_saved_query_title', table_name='saved_query')
    op.create_index(op.f('ix_saved_query_title'), 'saved_query', ['title'], unique=False)
    op.create_unique_constraint('key_unique_user_and_query', 'saved_query', ['user_id', 'query'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('key_unique_user_and_query', 'saved_query', type_='unique')
    op.drop_index(op.f('ix_saved_query_title'), table_name='saved_query')
    op.create_index('ix_saved_query_title', 'saved_query', ['title'], unique=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
